name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  nuxtjs:
    name: nuxt.js compile
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Install NodeJS v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Restore CI Cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-12-${{ hashFiles('**/yarn.lock') }}
      - name: Install Dependencies
        run: yarn --ignore-scripts
      - name: Build nuxt.js project
        run: yarn build
